version: "3.9"

services:
  airflow:
    image: lucasbustos/airflow:1.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - KEY_API=${KEY_API}
    container_name: airflow-football
    volumes: 
      - ${DATALAKE_FOLDER}:/datalake
    privileged: true
    ports:
      - '3000:8080' # Airflow webserver
      - '9001:9001' # Supervisord web interface